language: python
python:
  - "3.6"
  - "pypy3.5"
before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda install --yes numpy=1.8
install:
  - sudo apt-get update
script:
- nosetests -v
